name: Destroy-Azure-Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
      TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import VM
        run: |
          terraform import azurerm_linux_virtual_machine.vm /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/MYRESOURCEGROUP/providers/Microsoft.Compute/virtualMachines/EXAMPLE-VM
        # Replace resource ID with your actual VM resource ID if different

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
